tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "error-container": "#ffdad6",
                "surface-bright": "#f9f9f9",
                "secondary-fixed": "#ffe088",
                "surface": "#f9f9f9",
                "on-primary-fixed-variant": "#005227",
                "inverse-surface": "#2f3131",
                "outline-muted": "rgba(45, 52, 54, 0.08)",
                "on-error": "#ffffff",
                "tertiary-container": "#acb3b5",
                "on-secondary-fixed-variant": "#574500",
                "inverse-on-surface": "#f1f1f1",
                "emerald-deep": "#3DA960",
                "secondary-container": "#fed65b",
                "outline": "#6e7a6e",
                "surface-variant": "#e2e2e2",
                "secondary-fixed-dim": "#e9c349",
                "secondary": "#735c00",
                "primary-fixed-dim": "#66dd8b",
                "surface-container-highest": "#e2e2e2",
                "on-primary-container": "#005025",
                "on-tertiary-fixed-variant": "#41484a",
                "tertiary": "#586062",
                "on-error-container": "#93000a",
                "on-tertiary-container": "#3e4548",
                "primary": "#006d36",
                "gold-light": "#F1D592",
                "champagne-gold": "#F1D592",
                "midnight-blue": "#0A0F1E",
                "error": "#ba1a1a",
                "on-surface-variant": "#3e4a3f",
                "surface-container": "#eeeeee",
                "on-primary": "#ffffff",
                "on-primary-fixed": "#00210c",
                "on-secondary": "#ffffff",
                "background": "#f9f9f9",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#f3f3f3",
                "surface-container-lowest": "#ffffff",
                "on-background": "#1a1c1c",
                "on-secondary-container": "#745c00",
                "outline-variant": "#bdcabc",
                "on-surface": "#1a1c1c",
                "surface-container-high": "#e8e8e8",
                "surface-dim": "#dadada",
                "surface-glass": "rgba(255, 255, 255, 0.1)",
                "tertiary-fixed-dim": "#c1c8ca",
                "on-tertiary-fixed": "#161d1f",
                "inverse-primary": "#66dd8b",
                "on-secondary-fixed": "#241a00",
                "surface-tint": "#006d36",
                "primary-fixed": "#83fba5",
                "primary-container": "#50c878",
                "tertiary-fixed": "#dde4e6"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "container-max": "1440px",
                "section-padding": "160px",
                "unit": "8px",
                "margin-desktop": "80px",
                "gutter": "32px",
                "margin-mobile": "24px"
            },
            "fontFamily": {
                "label-sm": ["Inter"],
                "headline-xl-mobile": ["Inter"],
                "body-lg": ["Inter"],
                "headline-lg": ["Inter"],
                "display-lg": ["Inter"],
                "body-md": ["Inter"],
                "headline-xl": ["Inter"]
            },
            "fontSize": {
                "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600"}],
                "headline-xl-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                "body-lg": ["18px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400"}],
                "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.03em", "fontWeight": "600"}]
            }
        },
    },
};
